- name: Install vector
  hosts: vector
  tasks:
  - name: Get distrib
    ansible.builtin.get_url:
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
      dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
  - name: Install downloaded packages
    ansible.builtin.service:
      name: vector-{{ vector_version }}-1.x86_64.rpm
